name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: "Env to deploy"
        type: environment
        required: true
    
jobs:
  Build:
     runs-on: ubuntu-latest
     steps:
      - run: |
          echo "name of the event that triggered the workflow: ${{ github.event_name }}"
          echo "name of the branch that the repository is currently referencing:  ${{ github.ref }}"

      - uses: actions/checkout@v4.2.2

      - name: List files in the repository
        run: |
          echo "${{ github.repository }}"
          tree

  Test:
     runs-on: ubuntu-latest
     needs: Build
     if: github.event_name == 'workflow_dispatch'
     steps:
       - run: echo "Testing..."

  Load-Test:
      runs-on: ubuntu-latest
      needs: Build
      if: github.event_name == 'workflow_dispatch'
      steps:
        - run: |
            echo "🧪 Testing..."
            sleep 15

  Production:
      runs-on: ubuntu-latest
      needs: [Test, Load-Test]
      environment:
        name: Production
        url: https://writeabout.net
      if: github.event.inputs.environment == 'Production'
      steps:
        - run: |
            echo "Step x deploying..."
            sleep 10
        - run: |
            echo "Step x deploying..."
            sleep 10
        - run: |
            echo "Step x deploying..."
            sleep 10
        - run: |
            echo "Step x deploying..."
            sleep 10
        - run: |
            echo "Step x deploying..."
            sleep 10
          

      
