name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  Build:
     runs-on: ubuntu-latest
     steps:
      - run: |
          echo "name of the event that triggered the workflow: ${{ github.event_name }}"
          echo "name of the branch that the repository is currently referencing:  ${{ github.ref }}"

      - uses: actions/checkout@v4.2.2

      - name: List files in the repository
        run: |
          echo "${{ github.repository }}"
          tree

      
